server:
  port: 8083
  
spring:
  application:
    name: interest-calculator-ascg

security:
  basic:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: '*'
        
hystrix:
  threadpool:
    default:
      coreSize: 35
      maximumSize: 35
  command:
    createRevenueGrid:
      execution:
        isolation:
          thread: 
            timeoutInMilliseconds: 1500
          semaphore:
            maxConcurrentRequests: 500
      circuitBreaker:
        sleepWindowInMilliseconds: 5000
        